version: '3.9'

services:
  frontend:
    build:
      context: client
    image: frontend:0.1
    container_name: frontend
    ports:
      - 5173:5173
    environment:
      PUBLIC_GATEWAY_BASE_URL: http://gateway:8000/

  gateway:
    build:
      context: backend/gateway
    image: gateway:0.1
    container_name: gateway
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      JWT_SECRET: zeusemployeemanagementjwtsecret
      JWT_EXPIRES: 60
      JWT_IGNORE_EXPIRATION: true
      EMPLOYEES_URL: http://profile:8010
      FRONTEND_URL: http://frontend:5173

  profile:
    build:
      context: backend/profile
    image: profile:0.1
    container_name: profile
    ports:
      - 8010:8010
    environment:
      PORT: 8010
      MONGODB_URI: mongodb://localhost:27017
