version: "3.9"

services:
  frontend:
    build:
      context: client
    image: frontend:0.1
    container_name: frontend
    ports:
      - 5173:5173
    environment:
      PUBLIC_GATEWAY_BASE_URL: http://localhost:8000/

  gateway:
    build:
      context: backend/gateway
    image: gateway:0.1
    container_name: gateway
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      JWT_SECRET: zeusemployeemanagementjwtsecret
      JWT_EXPIRES: 60
      JWT_IGNORE_EXPIRATION: true
      EMPLOYEES_URL: http://profile:8010
      FRONTEND_URL: http://localhost:5173

  profile:
    build:
      context: backend/profile
    image: profile:0.1
    container_name: profile
    ports:
      - 8010:8010
    environment:
      PORT: 8010
      MONGODB_URI: mongodb+srv://<username>:<password>@zemcluster1.dz4rzdu.mongodb.net/employee?retryWrites=true&w=majority

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      # - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
